export const disposableEmailDomains = [
  "10minutemail.com",
  "20minutemail.com",
  "2prong.com",
  "33mail.com",
  "anonbox.net",
  "burnermail.io",
  "byom.de",
  "dispostable.com",
  "dropmail.me",
  "emailondeck.com",
  "fakeinbox.com",
  "fakemail.net",
  "getairmail.com",
  "getnada.com",
  "guerrillamail.com",
  "guerrillamail.net",
  "guerrillamail.org",
  "guerrillamailblock.com",
  "harakirimail.com",
  "incognitomail.org",
  "jetable.org",
  "mail-temporaire.fr",
  "mail.tm",
  "maildrop.cc",
  "maildrop.io",
  "mailforspam.com",
  "mailinator.com",
  "mailinator.net",
  "mailnesia.com",
  "mailnull.com",
  "mailsac.com",
  "moakt.com",
  "mytemp.email",
  "nada.email",
  "nwldx.com",
  "oneoffemail.com",
  "sharklasers.com",
  "spam4.me",
  "spamgourmet.com",
  "spambog.com",
  "temp-mail.io",
  "temp-mail.org",
  "temp-mail.ru",
  "tempail.com",
  "tempmail.dev",
  "tempmail.email",
  "tempmailo.com",
  "throwawaymail.com",
  "trashmail.com",
  "trashmail.de",
  "trashmail.fr",
  "yopmail.com",
  "yopmail.fr",
  "yopmail.net"
] as const;

export function isDisposableEmail(email: string) {
  const domain = email.split("@")[1]?.toLowerCase().trim();
  if (!domain) {
    return false;
  }

  return disposableEmailDomains.includes(domain as (typeof disposableEmailDomains)[number]);
}
